In [451]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import numpy
import sys

In [452]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.multiclass import OneVsRestClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from pandas.plotting import scatter_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [514]:
resumeDataSet = pd.read_csv(r'UpdatedResumeDataSet.csv' ,encoding='utf-8')

In [515]:
resumeDataSet

         Category                                             Resume
0    Data Science  Skills * Programming Languages: Python (pandas...
1    Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2    Data Science  Areas of Interest Deep Learning, Control Syste...
3    Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4    Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...
..            ...                                                ...
957       Testing  Computer Skills: â¢ Proficient in MS office (...
958       Testing  â Willingness to accept the challenges. â ...
959       Testing  PERSONAL SKILLS â¢ Quick learner, â¢ Eagerne...
960       Testing  COMPUTER SKILLS & SOFTWARE KNOWLEDGE MS-Power ...
961       Testing  Skill Set OS Windows XP/7/8/8.1/10 Database MY...

[962 rows x 2 columns]

In [516]:
resumeDataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 962 entries, 0 to 961
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  962 non-null    object
 1   Resume    962 non-null    object
dtypes: object(2)
memory usage: 15.2+ KB

In [519]:
categ = resumeDataSet['Category'].unique()
print (categ)

['Data Science' 'HR' 'Advocate' 'Arts' 'Web Designing'
 'Mechanical Engineer' 'Sales' 'Health and fitness' 'Civil Engineer'
 'Java Developer' 'Business Analyst' 'SAP Developer' 'Automation Testing'
 'Electrical Engineering' 'Operations Manager' 'Python Developer'
 'DevOps Engineer' 'Network Security Engineer' 'PMO' 'Database' 'Hadoop'
 'ETL Developer' 'DotNet Developer' 'Blockchain' 'Testing']

In [520]:
print (resumeDataSet['Category'].value_counts())

Java Developer               84
Testing                      70
DevOps Engineer              55
Python Developer             48
Web Designing                45
HR                           44
Hadoop                       42
Blockchain                   40
ETL Developer                40
Operations Manager           40
Data Science                 40
Sales                        40
Mechanical Engineer          40
Arts                         36
Database                     33
Electrical Engineering       30
Health and fitness           30
PMO                          30
Business Analyst             28
DotNet Developer             28
Automation Testing           26
Network Security Engineer    25
SAP Developer                24
Civil Engineer               24
Advocate                     20
Name: Category, dtype: int64

In [521]:
import re
def cleanResume(resumeText):
    resumeText = re.sub('http\S+\s*', ' ', resumeText)  # remove URLs
    resumeText = re.sub('RT|cc', ' ', resumeText)  # remove RT and cc
    resumeText = re.sub('#\S+', '', resumeText)  # remove hashtags
    resumeText = re.sub('@\S+', '  ', resumeText)  # remove mentions
    resumeText = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""), ' ', resumeText)  # remove punctuations
    resumeText = re.sub(r'[^\x00-\x7f]',r' ', resumeText) 
    resumeText = re.sub('\s+', ' ', resumeText)  # remove extra whitespace
    return resumeText
    
resumeDataSet['cleaned_resume'] = resumeDataSet.Resume.apply(lambda x: cleanResume(x))

In [522]:
resumeDataSet.head()

,Category,Resume,cleaned_resume
0,Data Science,Skills * Programming Languages: Python (pandas...,Skills Programming Languages Python pandas num...
1,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...,Education Details May 2013 to May 2017 B E UIT...
2,Data Science,"Areas of Interest Deep Learning, Control Syste...",Areas of Interest Deep Learning Control System...
3,Data Science,Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...,Skills R Python SAP HANA Tableau SAP HANA SQL ...
4,Data Science,"Education Details \r\n MCA YMCAUST, Faridab...",Education Details MCA YMCAUST Faridabad Haryan...

In [523]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
import string
from wordcloud import WordCloud

oneSetOfStopWords = set(stopwords.words('english')+['``',"''"])

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\TUNEZ-1\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\TUNEZ-1\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [524]:
print(resumeDataSet['Resume'])

0      Skills * Programming Languages: Python (pandas...
1      Education Details \r\nMay 2013 to May 2017 B.E...
2      Areas of Interest Deep Learning, Control Syste...
3      Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4      Education Details \r\n MCA   YMCAUST,  Faridab...
                             ...
957    Computer Skills: â¢ Proficient in MS office (...
958    â Willingness to accept the challenges. â ...
959    PERSONAL SKILLS â¢ Quick learner, â¢ Eagerne...
960    COMPUTER SKILLS & SOFTWARE KNOWLEDGE MS-Power ...
961    Skill Set OS Windows XP/7/8/8.1/10 Database MY...
Name: Resume, Length: 962, dtype: object

In [525]:
oneSetOfStopWords = set(stopwords.words('english')+['``',"''"])
totalWords =[]
Sentences = resumeDataSet['Resume'].values
cleanedSentences = ""
for records in Sentences:
    cleanedText = cleanResume(records)
    cleanedSentences += cleanedText
    requiredWords = nltk.word_tokenize(cleanedText)
    for word in requiredWords:
        if word not in oneSetOfStopWords and word not in string.punctuation:
            totalWords.append(word)
    
wordfreqdist = nltk.FreqDist(totalWords)
mostcommon = wordfreqdist.most_common(50)

In [464]:
print(mostcommon)

[('Exprience', 3829), ('months', 3233), ('company', 3130), ('Details', 2967), ('description', 2634), ('1', 2134), ('Project', 1808), ('project', 1579), ('6', 1499), ('data', 1438), ('team', 1424), ('Maharashtra', 1385), ('year', 1244), ('Less', 1137), ('January', 1086), ('using', 1041), ('Skill', 1018), ('Pune', 1016), ('Management', 1010), ('SQL', 990), ('Ltd', 934), ('management', 927), ('C', 896), ('Engineering', 855), ('Education', 833), ('Developer', 806), ('Java', 773), ('2', 754), ('development', 752), ('monthsCompany', 746), ('Pvt', 730), ('application', 727), ('System', 715), ('reports', 697), ('business', 696), ('India', 693), ('requirements', 693), ('I', 690), ('various', 688), ('A', 688), ('Data', 674), ('The', 672), ('University', 656), ('process', 648), ('Testing', 646), ('test', 638), ('Responsibilities', 637), ('system', 636), ('testing', 634), ('Software', 632)]

In [529]:
from sklearn.preprocessing import LabelEncoder
# prerocess encoding data 
var_mod = ['Category']
categ =resumeDataSet['Category'].unique()
L_categ = LabelEncoder().fit_transform(categ)
for i in var_mod:
    resumeDataSet[i] = LabelEncoder().fit_transform(resumeDataSet[i])
    
D ={}
for i in range(len(categ)):
    D[categ[i]] =  L_categ[i]
print(D)

{'Data Science': 6,
 'HR': 12,
 'Advocate': 0,
 'Arts': 1,
 'Web Designing': 24,
 'Mechanical Engineer': 16,
 'Sales': 22,
 'Health and fitness': 14,
 'Civil Engineer': 5,
 'Java Developer': 15,
 'Business Analyst': 4,
 'SAP Developer': 21,
 'Automation Testing': 2,
 'Electrical Engineering': 11,
 'Operations Manager': 18,
 'Python Developer': 20,
 'DevOps Engineer': 8,
 'Network Security Engineer': 17,
 'PMO': 19,
 'Database': 7,
 'Hadoop': 13,
 'ETL Developer': 10,
 'DotNet Developer': 9,
 'Blockchain': 3,
 'Testing': 23}

In [539]:
resumeDataSet.head()

,Category,Resume,cleaned_resume
0,6,Skills * Programming Languages: Python (pandas...,Skills Programming Languages Python pandas num...
1,6,Education Details \r\nMay 2013 to May 2017 B.E...,Education Details May 2013 to May 2017 B E UIT...
2,6,"Areas of Interest Deep Learning, Control Syste...",Areas of Interest Deep Learning Control System...
3,6,Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...,Skills R Python SAP HANA Tableau SAP HANA SQL ...
4,6,"Education Details \r\n MCA YMCAUST, Faridab...",Education Details MCA YMCAUST Faridabad Haryan...

In [531]:
resumeDataSet.Category.value_counts()

15    84
23    70
8     55
20    48
24    45
12    44
13    42
3     40
10    40
18    40
6     40
22    40
16    40
1     36
7     33
11    30
14    30
19    30
4     28
9     28
2     26
17    25
21    24
5     24
0     20
Name: Category, dtype: int64

In [532]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

requiredText = resumeDataSet['cleaned_resume'].values
requiredTarget = resumeDataSet['Category'].values

word_vectorizer = TfidfVectorizer( 
    sublinear_tf=True,
    stop_words='english')
word_vectorizer.fit(requiredText)
WordFeatures = word_vectorizer.transform(requiredText)

print ("Feature completed .....")

X_train,X_test,y_train,y_test = train_test_split(WordFeatures,requiredTarget,random_state=42, test_size=0.2,
                                                 shuffle=True, stratify=requiredTarget)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

Feature completed .....
(769, 7351)
(193, 7351)
(769,)
(193,)

In [533]:
word_vectorizer.vocabulary_

{'skills': 6080,
 'programming': 5160,
 'languages': 3713,
 'python': 5266,
 'pandas': 4742,
 'numpy': 4490,
 'scipy': 5857,
 'scikit': 5855,
 'learn': 3756,
 'matplotlib': 4069,
 'sql': 6239,
 'java': 3537,
 'javascript': 3539,
 'jquery': 3581,
 'machine': 3928,
 'learning': 3760,
 'regression': 5477,
 'svm': 6454,
 'na': 4344,
 've': 7038,
 'bayes': 821,
 'knn': 3656,
 'random': 5347,
 'forest': 2734,
 'decision': 1839,
 'trees': 6806,
 'boosting': 944,
 'techniques': 6568,
 'cluster': 1316,
 'analysis': 483,
 'word': 7266,
 'embedding': 2263,
 'sentiment': 5945,
 'natural': 4369,
 'language': 3712,
 'processing': 5118,
 'dimensionality': 2012,
 'reduction': 5450,
 'topic': 6722,
 'modelling': 4239,
 'lda': 3743,
 'nmf': 4446,
 'pca': 4822,
 'neural': 4419,
 'nets': 4412,
 'database': 1779,
 'visualizations': 7124,
 'mysql': 4342,
 'sqlserver': 6246,
 'cassandra': 1123,
 'hbase': 3034,
 'elasticsearch': 2236,
 'd3': 1758,
 'js': 3583,
 'dc': 1809,
 'plotly': 4952,
 'kibana': 3643,
 'ggplot': 2884,
 'tableau': 6486,
 'regular': 5478,
 'expression': 2516,
 'html': 3165,
 'css': 1710,
 'angular': 501,
 'logstash': 3888,
 'kafka': 3608,
 'flask': 2687,
 'git': 2892,
 'docker': 2085,
 'computer': 1455,
 'vision': 7111,
 'open': 4577,
 'cv': 1748,
 'understanding': 6910,
 'deep': 1854,
 'education': 2212,
 'details': 1948,
 'data': 1777,
 'science': 5850,
 'assurance': 660,
 'associate': 655,
 'ernst': 2372,
 'young': 7337,
 'llp': 3848,
 'skill': 6077,
 'exprience': 2518,
 '24': 118,
 'months': 4272,
 'monthscompany': 4273,
 'company': 1408,
 'description': 1928,
 'fraud': 2769,
 'investigations': 3466,
 'dispute': 2057,
 'services': 5966,
 'technology': 6573,
 'assisted': 651,
 'review': 5632,
 'tar': 6523,
 'assists': 654,
 'elerating': 2246,
 'process': 5115,
 'run': 5738,
 'analytics': 489,
 'generate': 2864,
 'reports': 5539,
 'core': 1607,
 'member': 4122,
 'team': 6557,
 'helped': 3058,
 'developing': 1964,
 'automated': 715,
 'platform': 4941,
 'tool': 6720,
 'scratch': 5868,
 'assisting': 653,
 'discovery': 2038,
 'domain': 2099,
 'implements': 3253,
 'predictive': 5048,
 'coding': 1336,
 'automating': 718,
 'reviews': 5636,
 'resulting': 5608,
 'reduced': 5448,
 'labor': 3693,
 'costs': 1631,
 'time': 6681,
 'spent': 6213,
 'lawyers': 3737,
 'understand': 6909,
 'end': 2288,
 'flow': 2700,
 'solution': 6155,
 'doing': 2094,
 'research': 5562,
 'development': 1965,
 'classification': 1284,
 'models': 4240,
 'mining': 4202,
 'information': 3333,
 'present': 5067,
 'text': 6620,
 'worked': 7272,
 'analyzing': 494,
 'outputs': 4684,
 'precision': 5043,
 'monitoring': 4265,
 'entire': 2333,
 'evidence': 2436,
 'following': 2720,
 'ey': 2540,
 'standards': 6285,
 'developed': 1960,
 'classifier': 1286,
 'order': 4621,
 'identify': 3204,
 'red': 5442,
 'flags': 2684,
 'related': 5491,
 'issues': 3510,
 'tools': 6721,
 'technologies': 6571,
 'tfidf': 6624,
 'word2vec': 7267,
 'doc2vec': 2084,
 'cosine': 1625,
 'similarity': 6050,
 'vader': 7001,
 'blob': 909,
 'matplot': 4068,
 'lib': 3797,
 'dashboard': 1775,
 'reporting': 5538,
 'multiple': 4318,
 'analytic': 486,
 'projects': 5169,
 'usa': 6964,
 'clients': 1297,
 'motor': 4285,
 'vehicle': 7042,
 'customer': 1738,
 'received': 5413,
 'feedback': 2617,
 'survey': 6448,
 'past': 4795,
 'year': 7325,
 'performed': 4843,
 'positive': 4996,
 'negative': 4392,
 'neutral': 4421,
 'series': 5957,
 'comments': 1381,
 'categories': 1129,
 'created': 1670,
 'heat': 3051,
 'map': 4015,
 'terms': 6608,
 'category': 1131,
 'based': 809,
 'frequency': 2780,
 'words': 7268,
 'extracted': 2532,
 'plotted': 4954,
 'cloud': 1310,
 'customized': 1743,
 'dashboards': 1776,
 'effective': 2218,
 'chatbot': 1213,
 'user': 6971,
 'friendly': 2785,
 'products': 5133,
 'handle': 3009,
 'simple': 6051,
 'questions': 5300,
 'hours': 3146,
 'operation': 4588,
 'reservation': 5565,
 'options': 4611,
 'chat': 1212,
 'bot': 947,
 'serves': 5964,
 'product': 5128,
 'giving': 2897,
 'overview': 4700,
 'qa': 5269,
 'recommendation': 5424,
 'responses': 5590,
 'question': 5298,
 'build': 1021,
 'chain': 1184,
 'relevant': 5505,
 'answer': 515,
 'intelligence': 3409,
 'pipeline': 4911,
 'requirement': 5557,
 'asks': 625,
 'recommended': 5426,
 'nltk': 4444,
 'spacy': 6186,
 'governance': 2937,
 'organizations': 4640,
 'make': 3971,
 'informed': 3334,
 'decisions': 1840,
 'store': 6327,
 'integrated': 3402,
 'portfolio': 4991,
 'synthesizes': 6480,
 'unstructured': 6935,
 'sources': 6177,
 'facilitates': 2554,
 'action': 286,
 'ensure': 2320,
 'best': 856,
 'positioned': 4995,
 'counter': 1638,
 'risk': 5669,
 'scan': 5818,
 'formats': 2740,
 'parse': 4765,
 'different': 2001,
 'file': 2635,
 'extract': 2531,
 'meta': 4147,
 'push': 5258,
 'results': 5609,
 'indexing': 3300,
 'elastic': 2235,
 'search': 5890,
 'interactive': 3420,
 'using': 6975,
 'preforming': 5053,
 'rot': 5704,
 'helps': 3060,
 'content': 1544,
 'redundant': 5451,
 'outdated': 4676,
 'trivial': 6827,
 'predefined': 5044,
 'methods': 4156,
 'tag': 6494,
 'pii': 4904,
 'personally': 4859,
 'identifiable': 3200,
 'social': 6130,
 'security': 5909,
 'numbers': 4487,
 'addresses': 315,
 'names': 4355,
 'frequently': 2782,
 'targeted': 6525,
 'cyber': 1754,
 'attacks': 678,
 'investigative': 3467,
 'flag': 2682,
 'cases': 1118,
 'fap': 2588,
 'inbuilt': 3273,
 'case': 1117,
 'manager': 3989,
 'suite': 6407,
 'various': 7025,
 'erp': 2373,
 'systems': 6483,
 'used': 6969,
 'interrogate': 3442,
 'ounting': 4671,
 'identifying': 3205,
 'anomalies': 512,
 'indicators': 3305,
 'running': 5740,
 'advanced': 344,
 'bootstrap': 946,
 'node': 4449,
 '2013': 96,
 '2017': 100,
 'uit': 6894,
 'rgpv': 5654,
 'scientist': 5854,
 'matelabs': 4059,
 'statsmodels': 6307,
 '12': 34,
 'aws': 745,
 'sklearn': 6083,
 'keras': 3633,
 'ml': 4221,
 'business': 1035,
 'professionals': 5139,
 'dummies': 2157,
 'enthusiasts': 2332,
 '60': 202,
 'koramangala': 3669,
 '5th': 201,
 'block': 910,
 'achievements': 274,
 'tasks': 6531,
 'sukh': 6410,
 'sagar': 5755,
 'bengaluru': 852,
 'india': 3301,
 'deployed': 1911,
 'auto': 711,
 'preprocessing': 5064,
 'steps': 6319,
 'mainly': 3959,
 'missing': 4213,
 'value': 7010,
 'treatment': 6804,
 'outlier': 4680,
 'detection': 1951,
 'encoding': 2284,
 'scaling': 5816,
 'feature': 2610,
 'selection': 5921,
 'model': 4236,
 'linkedin': 3825,
 'com': 1367,
 'aditya': 326,
 'rathore': 5360,
 'b4600b146': 759,
 'reasearch': 5398,
 'forecasting': 2729,
 'arima': 589,
 'sarimax': 5783,
 'holt': 3123,
 'winter': 7252,
 'prophet': 5187,
 'extracting': 2533,
 'problem': 5110,
 'github': 2894,
 'rathorology': 5361,
 'implemented': 3251,
 'state': 6296,
 'art': 604,
 'paper': 4748,
 'mixed': 4219,
 'attributes': 689,
 'areas': 584,
 'control': 1570,
 'design': 1930,
 'electric': 2238,
 'machinery': 3929,
 'web': 7203,
 'technical': 6563,
 'activities': 292,
 'hindustan': 3088,
 'aeronautics': 362,
 'limited': 3816,
 'bangalore': 787,
 'weeks': 7219,
 'guidance': 2983,
 'mr': 4299,
 'satish': 5795,
 'senior': 5935,
 'engineer': 2301,
 'hangar': 3019,
 'mirage': 4208,
 '2000': 78,
 'fighter': 2632,
 'aircraft': 399,
 'matlab': 4066,
 'labview': 3699,
 'webframework': 7205,
 'django': 2075,
 'ltspice': 3917,
 'intermediate': 3429,
 'mipower': 4207,
 'gitbash': 2893,
 'jupyter': 3605,
 'notebook': 4466,
 'xampp': 7302,
 'basics': 813,
 'software': 6138,
 'packages': 4718,
 'interpreters': 3441,
 'anaconda': 476,
 'python2': 5267,
 'python3': 5268,
 'pycharm': 5263,
 'ide': 3194,
 'eclipse': 2194,
 'operating': 4586,
 'windows': 7245,
 'ubuntu': 6882,
 'debian': 1828,
 'kali': 3613,
 'linux': 3828,
 'january': 3532,
 '2019': 102,
 'tech': 6561,
 'electrical': 2239,
 'electronics': 2243,
 'engineering': 2303,
 'manipal': 4000,
 'institute': 3387,
 '2015': 98,
 'deeksha': 1853,
 'center': 1159,
 'little': 3841,
 'flower': 2701,
 'public': 5229,
 'school': 5845,
 'august': 698,
 'academy': 266,
 'higher': 3075,
 'enthusiast': 2330,
 'excel': 2448,
 'mathematics': 4064,
 'themathcompany': 6647,
 'currently': 1730,
 'working': 7278,
 'casino': 1122,
 'operator': 4593,
 'disclosed': 2033,
 'macau': 3927,
 'need': 4389,
 'segment': 5913,
 'customers': 1739,
 'visit': 7112,
 'property': 5185,
 'patrons': 4808,
 'bring': 986,
 'basically': 812,
 'prove': 5205,
 'segmentation': 5914,
 'better': 857,
 'way': 7195,
 'current': 1729,
 'proper': 5182,
 'henceforth': 3061,
 'implement': 3248,
 'target': 6524,
 'marketing': 4032,
 'strategy': 6343,
 'attract': 685,
 'add': 305,
 'sap': 5779,
 'hana': 3006,
 'pal': 4736,
 'ms': 4303,
 'lumira': 3920,
 'linear': 3820,
 'advance': 343,
 'scm': 5858,
 'retail': 5612,
 'media': 4107,
 'nlp': 4443,
 '2018': 101,
 'pgdm': 4873,
 'great': 2957,
 'lakes': 3703,
 'management': 3985,
 'illinois': 3232,
 'bachelor': 761,
 'communication': 1399,
 'karnataka': 3621,
 'new': 4422,
 'horizon': 3135,
 'college': 1361,
 'visvesvaraya': 7127,
 'technological': 6570,
 'university': 6930,
 'consultant': 1529,
 'deloitte': 1890,
 'usi': 6974,
 'project': 5167,
 'involved': 3479,
 'analysing': 482,
 'historic': 3096,
 'deals': 1825,
 'coming': 1376,
 'insights': 3376,
 'optimize': 4606,
 'future': 2819,
 'role': 5691,
 'given': 2895,
 'raw': 5369,
 'carried': 1108,
 'presented': 5070,
 'client': 1296,
 'key': 3635,
 'responsibilities': 5591,
 'geographies': 2877,
 'infer': 3323,
 'meaningful': 4093,
 'prices': 5086,
 'blockades': 911,
 'environment': 2344,
 'industry': 3317,
 'cross': 1695,
 'service': 5965,
 'area': 583,
 'handwriting': 3016,
 'recognition': 5418,
 'taking': 6507,
 'handwritten': 3017,
 'images': 3235,
 'converting': 1587,
 'digital': 2005,
 'object': 4502,
 'sentence': 5944,
 'creation': 1673,
 'correction': 1617,
 'functionality': 2808,
 'gather': 2847,
 'large': 3719,
 'capture': 1094,
 'english': 2306,
 'train': 6761,
 'lstm': 3914,
 'finance': 2649,
 'financial': 2650,
 'bi': 872,
 'swift': 6460,
 'develop': 1959,
 'infrastructure': 3341,
 'view': 7086,
 'respective': 5583,
 'departments': 1904,
 'included': 3280,
 'expenses': 2487,
 'leading': 3750,
 'offshore': 4533,
 'etl': 2422,
 'validate': 7003,
 'ao': 521,
 'healthcare': 3046,
 'life': 3804,
 'sciences': 5851,
 'clinical': 1298,
 'argus': 586,
 'allow': 440,
 'users': 6972,
 'query': 5294,
 'faster': 2596,
 'provide': 5207,
 'capabilities': 1085,
 'deploy': 1910,
 'phase': 4879,
 'lot': 3904,
 'restructuring': 5606,
 'built': 1028,
 'analytical': 488,
 'fmcg': 2709,
 'trade': 6756,
 'promotion': 5176,
 'consumption': 1536,
 'planning': 4933,
 'flowers': 2702,
 'foods': 2724,
 'setting': 5976,
 'crm': 1691,
 'cbp': 1140,
 'modules': 4254,
 'decomposition': 1845,
 'base': 808,
 'forecast': 2728,
 'course': 1647,
 'performance': 4841,
 'improvements': 3268,
 'views': 7089,
 'sales': 5763,
 'funds': 2815,
 'bobj': 930,
 'internal': 3431,
 'initiative': 3348,
 'rfm': 5649,
 'interface': 3423,
 'su': 6368,
 'essfully': 2393,
 'segmented': 5915,
 'segments': 5916,
 'means': 4094,
 'algorithm': 423,
 'categorize': 1130,
 'defined': 1864,
 'buckets': 1012,
 'anaconda3': 477,
 'sps12': 6236,
 'telecom': 6578,
 'invoice': 3473,
 'reduce': 5447,
 'manual': 4008,
 'effort': 2225,
 'verifying': 7054,
 'closed': 1305,
 'invoices': 3475,
 'manually': 4009,
 'tree': 6805,
 'classify': 1287,
 'enabled': 2280,
 'enture': 2343,
 'experience': 2489,
 'developer': 1962,
 '19': 60,
 'solutions': 6156,
 'pvt': 5260,
 'ipa': 3489,
 'objects': 4505,
 'operational': 4589,
 'kpis': 3672,
 'spearheaded': 6195,
 'deployments': 1914,
 'introduced': 3457,
 'reuse': 5628,
 'functionalities': 2807,
 'prepared': 5062,
 'production': 5129,
 'designed': 1933,
 'attribute': 688,
 'calculation': 1059,
 'kpi': 3671,
 'individually': 3309,
 'complex': 1437,
 'scripts': 5875,
 'procedures': 5114,
 'took': 6719,
 'ownership': 4704,
 'building': 1025,
 'algorithms': 424,
 'executed': 2462,
 'server': 5960,
 'testing': 6614,
 'elerator': 2247,
 '21': 108,
 'taken': 6504,
 'care': 1102,
 'atas': 666,
 'completed': 1434,
 'apart': 527,
 'actively': 290,
 'maintenance': 3967,
 'servers': 5963,
 'quality': 5284,
 'requirements': 5558,
 'scope': 5861,
 'getting': 2882,
 'clarified': 1277,
 'interacting': 3418,
 'transform': 6774,
 'mapping': 4018,
 'documents': 2092,
 'reviewing': 5635,
 'specification': 6205,
 'documentation': 2088,
 'create': 1669,
 'update': 6941,
 'like': 3812,
 'tables': 6487,
 'stored': 6328,
 'function': 2805,
 'monitored': 4264,
 'error': 2375,
 'logs': 3887,
 'application': 542,
 'agent': 372,
 'diagrams': 1993,
 'entity': 2335,
 'relationship': 5498,
 'uml': 6900,
 'responsible': 5594,
 'designing': 1936,
 'normalization': 4456,
 'tuning': 6856,
 'profiler': 5147,
 'uat': 6880,
 'knowledge': 3659,
 'transfer': 6773,
 'support': 6436,
 '2008': 88,
 '2014': 97,
 'visual': 7121,
 'studio': 6365,
 '2010': 93,
 'monitor': 4263,
 'pl': 4922,
 'mca': 4086,
 'ymcaust': 7334,
 'faridabad': 2590,
 'haryana': 3027,
 'internship': 3437,
 'structure': 6358,
 'itechpower': 3511,
 'iot': 3487,
 'microsoft': 4176,
 'powerpoint': 5015,
 'academic': 265,
 'secured': 5906,
 'place': 4923,
 'ghatkesar': 2886,
 'andhra': 497,
 'pradesh': 5031,
 'aurora': 700,
 'scientific': 5853,
 'june': 3598,
 '2012': 95,
 'secondary': 5898,
 'warangal': 7175,
 'telangana': 6577,
 'sr': 6249,
 'junior': 3601,
 'office': 4525,
 'visualization': 7123,
 'statistics': 6305,
 'iabac': 3184,
 'certified': 1178,
 'versatile': 7056,
 'years': 7327,
 'managing': 3994,
 'consulting': 1532,
 'innovation': 3357,
 'bringing': 987,
 'ideas': 3197,
 'real': 5391,
 'world': 7286,
 'strong': 6356,
 'advocator': 357,
 'augmented': 697,
 'era': 2368,
 'human': 3172,
 'enhanced': 2308,
 'machines': 3930,
 'fahed': 2572,
 'passionate': 4791,
 'concepts': 1462,
 'ai': 392,
 'robotics': 5686,
 'mohali': 4256,
 'punjab': 5244,
 'indo': 3311,
 'global': 2903,
 'datamites': 1788,
 '13': 41,
 'analyzed': 492,
 'processed': 5116,
 'sets': 5975,
 'querying': 5296,
 'loading': 3857,
 'validation': 7005,
 'manipulating': 4001,
 'cleaning': 1288,
 'heretic': 3062,
 'closely': 1306,
 'propose': 5190,
 'making': 3974,
 'cleansing': 1289,
 'drawing': 2127,
 'conclusions': 1473,
 'recommendations': 5425,
 'statistical': 6304,
 'produce': 5123,
 'problems': 5112,
 'rayat': 5371,
 'bahra': 772,
 'biotechnology': 892,
 'tensorflow': 6600,
 'gcp': 2853,
 'network': 4416,
 'wipro': 7254,
 'bhawana': 868,
 'aggarwal': 374,
 'mail': 3954,
 'chd': 1217,
 'phone': 4885,
 '09876971076': 13,
 'vversatile': 7153,
 'high': 3074,
 'energy': 2295,
 'professional': 5136,
 'targeting': 6526,
 'challenging': 1187,
 'assignments': 647,
 'profile': 5145,
 'summary': 6412,
 'skilled': 6078,
 'inception': 3275,
 'specs': 6209,
 'implementation': 3249,
 'configuration': 1488,
 'libraries': 3798,
 'seaborn': 5885,
 'cufflinks': 1720,
 'bias': 874,
 'variance': 7020,
 'vector': 7039,
 'logistic': 3881,
 'networks': 4418,
 'unsupervised': 6936,
 'supervised': 6425,
 'reinforcement': 5488,
 'relational': 5495,
 'platforms': 4942,
 'oracle': 4613,
 'google': 2930,
 'good': 2928,
 'interpersonal': 3438,
 'solving': 6160,
 'ability': 256,
 'think': 6653,
 'laterally': 3724,
 'medium': 4115,
 'term': 6605,
 'long': 3891,
 'perspective': 4861,
 'flexibility': 2691,
 'attitude': 683,
 'change': 1192,
 'define': 1863,
 'frameworks': 2765,
 'emphasis': 2270,
 'code': 1330,
 'reusability': 5626,
 'clustering': 1317,
 'databases': 1780,
 'window': 7244,
 'environments': 2346,
 'netbeans': 4406,
 'notebooks': 4467,
 'sublime': 6378,
 'ticketing': 6667,
 'remedy': 5514,
 'ug': 6889,
 'passed': 4788,
 '78': 220,
 '2016': 99,
 'schooling': 5846,
 'xii': 7307,
 'moti': 4279,
 'ram': 5343,
 'arya': 614,
 'valley': 7008,
 'cgpa': 1182,
 'work': 7269,
 'experince': 2492,
 'title': 6695,
 'size': 6073,
 'brief': 983,
 'harnesses': 3024,
 'power': 5012,
 'automation': 719,
 'artificial': 610,
 'cognitive': 1338,
 'comprises': 1453,
 'layers': 3740,
 'engagement': 2297,
 'easily': 2183,
 'ess': 2387,
 'manage': 3982,
 'structured': 6359,
 'intent': 3414,
 'assessment': 639,
 'reasoning': 5402,
 'engine': 2300,
 'includes': 3281,
 'sense': 5937,
 'act': 284,
 'entailed': 2324,
 'queries': 5293,
 'earliest': 2178,
 'monster': 4269,
 'answered': 516,
 'quickly': 5305,
 'alll1': 435,
 'eliminated': 2255,
 'extractor': 2535,
 'involves': 3481,
 'extraction': 2534,
 'fetching': 2625,
 'important': 3258,
 'dates': 1795,
 'places': 4925,
 'contact': 1537,
 'regex': 5467,
 'bluemix': 920,
 'nlu': 4445,
 'api': 532,
 'tensor': 6599,
 'entities': 2334,
 'classifications': 1285,
 'classes': 1281,
 'training': 6766,
 'dataset': 1790,
 'predicting': 5047,
 'output': 4683,
 'mnb': 4228,
 'sgd': 5986,
 'optimization': 4605,
 'suited': 6408,
 'response': 5589,
 'efficient': 2222,
 'ner': 4401,
 'trained': 6762,
 'roles': 5692,
 'rnn': 5680,
 'bidirectional': 877,
 'framework': 2764,
 'diabetes': 1987,
 'detect': 1950,
 'person': 4855,
 'suffering': 6394,
 'got': 2935,
 'prize': 5105,
 'ce': 1154,
 'ifications': 3219,
 'organization': 4638,
 'udemy': 6885,
 'coursera': 1648,
 'personal': 4856,
 'father': 2599,
 'tirlok': 6692,
 'known': 3660,
 'hindi': 3086,
 'marital': 4030,
 'status': 6308,
 'single': 6061,
 'date': 1793,
 'birth': 895,
 'gender': 2860,
 '1993': 66,
 '20': 77,
 'yyyy': 7340,
 'mm': 4224,
 'dd': 1812,
 'programs': 5161,
 'grasp': 2953,
 'aspects': 630,
 'willingness': 7238,
 'levels': 3786,
 'result': 5607,
 'oriented': 4648,
 'master': 4055,
 'bhopal': 870,
 'madhya': 3935,
 'truba': 6834,
 'rkdf': 5673,
 '2006': 85,
 'polytechnic': 4984,
 'vidisha': 7078,
 'sati': 5789,
 '2003': 82,
 'thesis': 6651,
 'bmch': 923,
 'ganj': 2837,
 'basoda': 815,
 'month': 4270,
 'leaning': 3755,
 'scraping': 5866,
 'subjects': 6376,
 'crawling': 1668,
 'rnt': 5681,
 'practical': 5023,
 'recurrent': 5441,
 'custom': 1737,
 'apply': 547,
 'matplotliv': 4070,
 'comfort': 1373,
 'leave': 3765,
 'technique': 6567,
 'tf': 6623,
 ...}

In [534]:
print(WordFeatures)

  (0, 7337)	0.08595035648108577
  (0, 7325)	0.01794738101522041
  (0, 7272)	0.020357950474954145
  (0, 7268)	0.09054194474658708
  (0, 7267)	0.05901636533425517
  (0, 7266)	0.0671174150548629
  (0, 7124)	0.09992339257258985
  (0, 7111)	0.04181705520237126
  (0, 7042)	0.04643183419927338
  (0, 7038)	0.08733911322267127
  (0, 7025)	0.019637094364393735
  (0, 7001)	0.05901636533425517
  (0, 6975)	0.018887012833335267
  (0, 6971)	0.050387636670751676
  (0, 6969)	0.02405607482490523
  (0, 6964)	0.0334886388626349
  (0, 6935)	0.05347553112107107
  (0, 6910)	0.027471268153022293
  (0, 6909)	0.029708467825895302
  (0, 6827)	0.05901636533425517
  (0, 6806)	0.05901636533425517
  (0, 6722)	0.12389693304014394
  (0, 6721)	0.04933752996212628
  (0, 6720)	0.0704950032736423
  (0, 6681)	0.03754899576311922
  :	:
  (961, 1599)	0.07461695617520134
  (961, 1408)	0.02199327707894762
  (961, 1361)	0.07108885544761613
  (961, 1297)	0.09377219083098609
  (961, 1203)	0.10612923976586894
  (961, 1118)	0.10825821928693759
  (961, 1019)	0.07073242581634273
  (961, 1018)	0.08936728242823797
  (961, 966)	0.12035069017083998
  (961, 809)	0.1098143000993954
  (961, 719)	0.061195349445188923
  (961, 682)	0.08535743391220345
  (961, 680)	0.1556979498900352
  (961, 542)	0.09273845351991426
  (961, 510)	0.09036714901797487
  (961, 499)	0.19073166803634822
  (961, 494)	0.06230917109338399
  (961, 118)	0.10825821928693759
  (961, 99)	0.04657034134932821
  (961, 95)	0.05667114563829721
  (961, 94)	0.06603523145160058
  (961, 90)	0.07136995674663238
  (961, 88)	0.06393904825871972
  (961, 84)	0.07842776915112742
  (961, 15)	0.13444874731099185

In [535]:
clf = OneVsRestClassifier(KNeighborsClassifier())
clf.fit(X_train, y_train)
prediction = clf.predict(X_test)
print('Accuracy of KNeighbors Classifier on training set: {:.2f}'.format(clf.score(X_train, y_train)))
print('Accuracy of KNeighbors Classifier on test set:     {:.2f}'.format(clf.score(X_test, y_test)))

Accuracy of KNeighbors Classifier on training set: 0.99
Accuracy of KNeighbors Classifier on test set:     0.98

In [536]:
print("\n Classification report for classifier %s:\n%s\n" % (clf, metrics.classification_report(y_test, prediction)))

 Classification report for classifier OneVsRestClassifier(estimator=KNeighborsClassifier()):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         7
           2       0.75      0.60      0.67         5
           3       1.00      1.00      1.00         8
           4       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         5
           6       0.89      1.00      0.94         8
           7       1.00      0.86      0.92         7
           8       1.00      0.91      0.95        11
           9       1.00      1.00      1.00         5
          10       1.00      1.00      1.00         8
          11       0.86      1.00      0.92         6
          12       1.00      1.00      1.00         9
          13       1.00      1.00      1.00         8
          14       1.00      1.00      1.00         6
          15       1.00      1.00      1.00        17
          16       1.00      1.00      1.00         8
          17       1.00      1.00      1.00         5
          18       1.00      1.00      1.00         8
          19       1.00      1.00      1.00         6
          20       1.00      1.00      1.00        10
          21       1.00      1.00      1.00         5
          22       1.00      1.00      1.00         8
          23       0.93      1.00      0.97        14
          24       1.00      1.00      1.00         9

    accuracy                           0.98       193
   macro avg       0.98      0.97      0.97       193
weighted avg       0.98      0.98      0.98       193

In [540]:
F = open(r"C:\Users\TUNEZ-1\Desktop\tests nlp\testresume.txt","r")
X = F.readlines()
ch =""
for i in X:
    ch = ch + i
print(ch)
ch = [cleanResume(ch)]
WordFeatures = word_vectorizer.transform(ch)
f.close()

Formation _________________________________________________________________
Cycle d'ingÃ©nieur en science des donnÃ©es sept. 2020 - prÃ©sent
universitÃ© tek-up
Licence fondamentale en science de l'informatique sept. 2017 - juil. 2020
Institut supÃ©rieur des technologies e l'information et de la communication (ISTIC), Borj CÃ©dria
BaccalaurÃ©at informatique sept. 2016 - juin 2017
ExpÃ©rience professionnelle _____________________________________________________
Math universe â€“ Mourouj. Ben Arous janv. 2021 - prÃ©sent
Enseignant informatique
 Enseigner la matiÃ¨re informatique (Algorithme et Python) pour les niveaux (1Ã©re, 2Ã¨me, 3Ã¨me, bac) rÃ©gime tunisien.
Math universe â€“ Mourouj. Ben Arous sept.2020 - dec.2020
Conseiller numÃ©rique
 accompagner les publics dans leurs usages quotidiens du numÃ©rique notamment dans leurs dÃ©marches administratives en ligne.
Smartness â€“ Tunis. Tunis janv. 2020 â€“ juin.2020
Stagiaire
DÃ©veloppement et conception d'un agent conversationnel (Batbout Chatbot) bilingue (Tunisien/FranÃ§ais) qui suggÃ¨re une liste des recettes et des
restaurants selon les besoins
 CrÃ©ation d'un script d'extraction du contenu de sites tunisiens Marmiton, tripadvisor (Scrapy, selenuim)
 DÃ©veloppement d'un algorithme pour la prise de dÃ©cision (python, rasa_nlu, MongoDB)
 IntÃ©gration du chatbot dans la plateforme Facebook Messenger (Flask, Facebook graph API)
Beecoop â€“ Sousse. Sousse aoÃ»t 2018 - sept. 2018
stagiaire
DÃ©veloppement d'une application web de gestion de demande de stage (Html5, Php, Css3, Javascript)
Certification ________________________________________________________________
Amazon cloud practitioner avril 2022
PCAP (Certified Associate in Python Programming) avril 2022
IBM Big Data Engineer - Mastery Award 2020 juin 2020
TCF - Institut franÃ§ais 467/699 dec .2020
Projet _____________________________________________________________________
systÃ¨me automatique de reconnaissance de la langue de signes arabe
 CrÃ©ation dâ€™un algorithme DÃ©tection/suivre le mouvement de la main (Mediapipe, Cv2, Python)
 CrÃ©ation dâ€™un modÃ¨le de reconnaissance rÃ©seau de neurones convolutifs (TensorFlow)
LinkedIn job Scrapper (GitHub)
 Beautifullsoup , selenium , python
tableau de bord et un modÃ¨le de prÃ©diction des Accident Vasculaire CÃ©rÃ©brale. GitHub
CrÃ©ation dâ€™un tableau de bord (SSMS, Power Bi)
Analyse / nettoyage des donnÃ©es et la crÃ©ation du model de prÃ©diction (Python)
 CrÃ©ation et dÃ©ploiement dâ€™une application web (Flask, Html, Css)
CompÃ©tences en programmation : Python, Java ,PHP, SQL, Nosql, R
Autre : Git, HTML, CSS/BOOTSTAP, Apache spark, MapReduce, CV2, AWS services, docker, Machine learning, Deep learning, Flask
intÃ©rÃªts : CrÃ©ation des vidÃ©os Ã©ducative ( youtube : Joycode academy ), sports, jeu vidÃ©o

In [541]:
WordFeatures = word_vectorizer.transform(ch)
predicted_classe = {i for i in D if D[i]==clf.predict(WordFeatures)}
predicted_classe

{'Python Developer'}

0       6
1       6
2       6
3       6
4       6
       ..
957    23
958    23
959    23
960    23
961    23
Name: Category, Length: 962, dtype: int32

In [269]:
import pickle
with open('classifier.pickle','wb') as f:
    pickle.dump(clf,f)
    

with open('tfidfmodel.pickle','wb') as f:
    pickle.dump(vectorizer,f)

NameError: name 'vectorizer' is not defined